// AUTO-GENERATED by scripts/gen-version.mjs — 请勿手动编辑。
// 该文件在 predev / prebuild 阶段由 git 信息自动生成，每次部署都会刷新。
export const APP_VERSION = "20260714-1492b61";
export const APP_COMMIT_SHA = "1492b61";
export const APP_BUILD_DATE = "20260714";
