// 构建时自动生成应用版本号（每次部署刷新）
// 取 git 短哈希 + 最近提交日期，写入 src/lib/version.ts 供前端展示。
// 通过 package.json 的 predev / prebuild 钩子在 dev / build 前自动执行。
import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, "../src/lib/version.ts");

function sh(cmd, fallback) {
  try {
    return execSync(cmd, { encoding: "utf8" }).trim();
  } catch {
    return fallback;
  }
}

const shortSha = sh("git rev-parse --short HEAD", "unknown");
const date = sh("git log -1 --format=%cd --date=format:%Y.%m.%d", "dev");
const version = `${date}-${shortSha}`;

const content = `// AUTO-GENERATED by scripts/gen-version.mjs — 请勿手动编辑。
// 该文件在 predev / prebuild 阶段由 git 信息自动生成，每次部署都会刷新。
export const APP_VERSION = "${version}";
export const APP_COMMIT_SHA = "${shortSha}";
export const APP_BUILD_DATE = "${date}";
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content, "utf8");
console.log(`[gen-version] APP_VERSION = ${version}`);
